---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-cluster-1.8-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    operatorNamespace: ${releaseNamespace}
    toolbox:
      enabled: true
    monitoring:
      enabled: true
    ingress:
      dashboard: 
        className: ""
        annotations:
          kubernetes.io/ingress.class: kommander-traefik
          ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: "${workspaceNamespace}-stripprefixes@kubernetescrd,${workspaceNamespace}-forwardauth@kubernetescrd"
        paths:
          - "/dkp/rook/dashboard/"
        hosts:
          - ""
        tls: []
    cephBlockPools:
      storageClass:
        enabled: true
        name: ceph-block
    cephFileSystems:
      storageClass:
        enabled: true
        name: ceph-filesystem
    cephObjectStorage:
      storageClass:
        enabled: true
        name: ceph-bucket
