---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: management
    kustomize.toolkit.fluxcd.io/namespace: kommander-flux
  name: helm.goharbor.io
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: helm.goharbor.io
        namespace: kommander-flux
      version: "1.9.3"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: harbor
  valuesFrom:
    - kind: ConfigMap
      name: harbor-2.5.0-d2iq-defaults
  targetNamespace: ${releaseNamespace}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "harbor"
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "harbor"
data:
  name: "Harbor"
  dashboardLink: "/dkp/harbor/dashboard/"
  version: "2.5.0"
  category: "tools"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- nonResourceURLs:
  - /dkp/harbor/dashboard
  - /dkp/harbor/dashboard/*
  verbs:
  - get
  - head
  - post
  - put

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- nonResourceURLs:
  - /dkp/harbor/dashboard
  - /dkp/harbor/dashboard/*
  verbs:
  - get
  - head
  - post
  - put
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- nonResourceURLs:
  - /dkp/harbor/dashboard
  - /dkp/harbor/dashboard/*
  verbs:
  - get
  - head
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.middlewares: ${releaseNamespace}-stripprefixes@kubernetescrd,${releaseNamespace}-forwardauth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: harbor
  namespace: ${releaseNamespace}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: harbor-portal
            port:
              number: 80
        path: /dkp/harbor/dashboard
        pathType: ImplementationSpecific
