---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: management
    kustomize.toolkit.fluxcd.io/namespace: kommander-flux
  name: charts.chaos-mesh.org
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: https://charts.chaos-mesh.org
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: chaos-mesh
      sourceRef:
        kind: HelmRepository
        name: charts.chaos-mesh.org
        namespace: kommander-flux
      version: "2.1.3"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: chaos-mesh
  valuesFrom:
    - kind: ConfigMap
      name: chaos-mesh-2.1.3-d2iq-defaults
  targetNamespace: ${releaseNamespace}
