---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: management
    kustomize.toolkit.fluxcd.io/namespace: kommander-flux
  name: charts.rook.io
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: charts.rook.io
        namespace: kommander-flux
      version: "1.8"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: rook-ceph-cluster
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-cluster-1.8-d2iq-defaults
  targetNamespace: ${releaseNamespace}