---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper-policy-manager-1.0.1-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    ingress:
      enabled: false
    service:
      port: 80
      type: ClusterIP
    config:
      multicluster:
        enabled: false
      oidc:
        enabled: false
    rbac:
      create: true