---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper-policy-manager-0.3.0-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    ingress:
      enabled: false
    service:
      port: 80
      type: ClusterIP
    config:
      secretKey: randomkey
      multicluster:
        enabled: false
      oidc:
        enabled: false
    rbac:
      create: true