---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: management
    kustomize.toolkit.fluxcd.io/namespace: kommander-flux
  name: openebs-jiva
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: https://openebs.github.io/jiva-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-jiva
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: jiva
      sourceRef:
        kind: HelmRepository
        name: openebs-jiva
        namespace: kommander-flux
      version: "3.1.0"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: openebs-jiva
  valuesFrom:
    - kind: ConfigMap
      name: openebs-jiva-3.1.0-d2iq-defaults
  targetNamespace: ${releaseNamespace}