---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: management
    kustomize.toolkit.fluxcd.io/namespace: kommander-flux
  name: charts.rook.io
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: charts.rook.io
        namespace: kommander-flux
      version: "1.8.5"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: rook-ceph-cluster
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-cluster-1.8.5-d2iq-defaults
  targetNamespace: ${releaseNamespace}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "rook-ceph-cluster"
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "rook-ceph-cluster"
data:
  name: "Rook Ceph Cluster"
  dashboardLink: "/dkp/rook/dashboard/"
  version: "1.8.5"
  category: "Storage"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rook-ceph-cluster-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- nonResourceURLs:
  - /dkp/rook/dashboard
  - /dkp/rook/dashboard/*
  verbs:
  - get
  - head
  - post
  - put

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rook-ceph-cluster-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- nonResourceURLs:
  - /dkp/rook/dashboard
  - /dkp/rook/dashboard/*
  verbs:
  - get
  - head
  - post
  - put
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rook-ceph-cluster-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- nonResourceURLs:
  - /dkp/rook/dashboard
  - /dkp/rook/dashboard/*
  verbs:
  - get
  - head
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.middlewares: ${releaseNamespace}-stripprefixes@kubernetescrd,${releaseNamespace}-forwardauth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: rook-ceph-dashboard
  namespace: ${releaseNamespace}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 8443
        path: /dkp/rook/dashboard
        pathType: ImplementationSpecific
